services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POETRY_INSTALL_ARGS=--extras cpu
    environment:
      - LOG_LEVEL=INFO
      - DEVICE=cpu
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
      - MODEL_IDLE_TIMEOUT=60
      - TRANSLATION_MODEL_NAME=facebook/mbart-large-50-many-to-many-mmt
      - TRANSLATION_MODEL_DOWNLOAD_PATH=downloaded_translation_models
    ports:
      - "8000:8000"
    volumes:
      - ./volume/downloaded_translation_models:/app/downloaded_translation_models
